export const TOKEN_NAME ="name_token"
export const TOKEN_EMAIL ="email_token"
export const TOKEN_ROLE ="role_token"
export const TOKEN_EMP_ID ="empID_token"
export const TOKEN_JWT ="jwt_token"
export const TOKEN_REFRESH ="refresh_token"